/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUsdtSwapFactory } from "./IUsdtSwapFactory";
export type { IUsdtSwapPool } from "./IUsdtSwapPool";
