import type { NextPage } from "next";

/** components */
import PageLayout from "../components/PageLayout";
import ContentLayout from "../components/ContentLayout";
import SellPage from "../components/SellPage";

const pageConfig = {
  title: "USDT Swap",
  description: "Generated by @rainbow-me/create-rainbowkit",
};

const contentConfig = {
  title: "Sell",
  back: "",
};

const Home: NextPage = () => {
  return (
    <PageLayout pageConfig={pageConfig}>
      <ContentLayout contentConfig={contentConfig}>
        <SellPage />
      </ContentLayout>
    </PageLayout>
  );
};

export default Home;
