import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

/** components */
import Footer from "../components/Footer";
import InfoCard from "../components/InfoCard";
import NavList from "../components/NavList";
import SwapPage from "../components/SwapPage";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>USDT Swap</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.outerLayer}>
            {/* Sider */}
            <div className={styles.sider}>
              <InfoCard />
              <NavList />
            </div>
            {/* Content */}
            <div className={styles.content}>
              <SwapPage />
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
