import type { NextPage } from "next";
import { PageConfig, ContentConfig } from "../constants/type";

/** components */
import PageLayout from "../components/PageLayout";
import ContentLayout from "../components/ContentLayout";

const pageConfig: PageConfig = {
  title: "USDT Swap",
  description: "Generated by @rainbow-me/create-rainbowkit",
};

const contentConfig: ContentConfig = {
  title: "Sell",
  back: "",
};

const Sell: NextPage = () => {
  return (
    <PageLayout pageConfig={pageConfig}>
      <ContentLayout contentConfig={contentConfig}>
        <div>Sell</div>
      </ContentLayout>
    </PageLayout>
  );
};

export default Sell;
