import type { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { PageConfig, ContentConfig, TokenListItem } from "../constants/type";
import sty from "../styles/tokenList.module.scss";
import { CURRENT_TOKEN_LIST } from "../constants/tokenListJson";

/** components */
import PageLayout from "../components/PageLayout";
import ContentLayout from "../components/ContentLayout";

const pageConfig: PageConfig = {
  title: "Token List",
  description: "Generated by @rainbow-me/create-rainbowkit",
};

const contentConfig: ContentConfig = {
  title: "Token List",
  back: "",
};

const TokenList: NextPage = () => {
  const router = useRouter();
  const [list, setList] = useState<TokenListItem[] | undefined>();

  useEffect(() => {
    if (!!CURRENT_TOKEN_LIST) {
      setList(CURRENT_TOKEN_LIST.map((item: any, index: number) => item));
    }
  }, []);

  const onClick = (poolAddress: string) => {
    router.push({
      pathname: "/buy",
      query: {
        listPool: poolAddress,
      },
    });
  };

  return (
    <PageLayout pageConfig={pageConfig}>
      <ContentLayout contentConfig={contentConfig}>
        <div className={sty.tokenList}>
          <>
            <div className={sty.tokenList}>
              <table className={sty.list}>
                <thead>
                  <tr>
                    <th>Icon</th>
                    <th>Name</th>
                    <th>Token</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {!!list &&
                    list.map((item: TokenListItem, index: number) => (
                      <tr key={index}>
                        <td>
                          <img src={`${item.icon}`} width={25} height={25} />
                        </td>
                        <td>
                          <span className={sty.name} title={item.symbol}>
                            {item.name}
                          </span>
                        </td>
                        <td>
                          <span className={sty.address} title={item.token}>
                            {item.token}
                          </span>
                        </td>
                        <td>
                          <button className={sty.button} onClick={() => onClick(item.pool)} title={`Pool:${item.pool}`}>
                            Buy
                          </button>
                        </td>
                      </tr>
                    ))}
                </tbody>
              </table>
            </div>
          </>
        </div>
      </ContentLayout>
    </PageLayout>
  );
};

export default TokenList;
